spring:
  application:
    name: bank
  datasource:
    url: jdbc:mysql://localhost:3306/rggl
    username: root
    password: 12345678
  rabbitmq:
    password: 12345678
    username: krowfeather
    virtual-host: /kf
    host: 127.0.0.1
    port: 5672
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
server:
  port: 8082

